### ISSUE TITLE
Invalid metadata in pip package

### ISSUE THREAD

**Issue by murty0** [looking-for-a-job/pgrep.py#1]
We are getting the following error when trying to install this package (via `requirements.txt`):

```
ERROR: Requested pgrep==2020.7.1 from https://files.pythonhosted.org/packages/04/cd/ac18e02ab47028a85b80abacb770b1432b22c331b6f2240d48d57c1ee313/pgrep-2020.7.1.tar.gz#sha256=277d75948dcbd6200bf0ef6a0fb1082eb9469ffbc9ac5fab613974e8ff62db9d (from -r requirements.txt (line 17)) has different version in metadata: '0.0.0'
```

I believe this is caused by the new stricter pip resolver. More context can be found in these issues:
https://github.com/pypa/pip/issues/8917
https://github.com/pypa/pip/issues/8745

**Comment by andrewpetrochenkov** [comment]
wow. thanks for detailed info. fixed

**Comment by murty0** [comment]
Thanks @andrewp-as-is for the swift turnaround here!

I am still seeing the same issue though, and noticed that the pip package is still being pulled from the same URL: https://files.pythonhosted.org/packages/04/cd/ac18e02ab47028a85b80abacb770b1432b22c331b6f2240d48d57c1ee313/pgrep-2020.7.1.tar.gz#sha256=277d75948dcbd6200bf0ef6a0fb1082eb9469ffbc9ac5fab613974e8ff62db9d

I think you will need to update the package there!

**Comment by andrewpetrochenkov** [comment]
idk, maybe pip/pypi cache/error. it works on my computer
```python
pip3 install pgrep
Collecting pgrep
  Downloading pgrep-2020.12.3.tar.gz (1.3 kB)
Building wheels for collected packages: pgrep
  Building wheel for pgrep (setup.py) ... done
  Created wheel for pgrep: filename=pgrep-2020.12.3-py3-none-any.whl size=1357 sha256=b60f35abf7fc0b6c1b7d43869567aca91d824f66437e2b6994fab7372b10690b
  Stored in directory: /private/var/folders/t8/6x3s8whx545fr5dx07k81y_r0000gn/T/pip-ephem-wheel-cache-s8fqlwl5/wheels/b7/0a/82/90a9c85ea6934101b618483bc4d855f1adfd0c3591d64c4e31
Successfully built pgrep
Installing collected packages: pgrep
Successfully installed pgrep-2020.12.3
```

```
https://pypi.org/project/pgrep/#files
https://files.pythonhosted.org/packages/e9/ad/a2f2e4238f4228764eab4d8e8b57fb26cd917ea56bcd421fe51a5c6d4250/pgrep-2020.12.3.tar.gz
```

**Comment by murty0** [comment]
Hey! The issue seems to have been resolved! Thanks for your help here!
